export type Verdict = 'legal' | 'illegal'

export interface RightCard {
  id: string
  /** The bold scenario shown on the front of the card, phrased as a yes/no judgement. */
  scenario: string
  /** The correct answer: is the described action legal (compliant) or illegal? */
  verdict: Verdict
  /** The precise law that applies, e.g. "Section 130, Motor Vehicles Act". */
  law: string
  /** A quick, conversational 2-sentence rule explaining what to do. */
  rule: string
  /** A short visual illustration prompt (used by the AI ingestor output). */
  illustrationPrompt?: string
  /** Marks cards that were generated by the AI Card Ingestor. */
  generated?: boolean
}

export type PackId =
  | 'traffic'
  | 'tenant'
  | 'consumer'
  | 'arrest'
  | 'ingested'

export interface Pack {
  id: PackId
  name: string
  tagline: string
  /** lucide-react icon name resolved in the UI. */
  icon: string
  /** two-stop gradient used for the pack's cards, as tailwind color values. */
  gradient: [string, string]
  cards: RightCard[]
}
